/**
 * Preview Node Component
 *
 * Visualizes a streaming preview node that is being generated by an agent.
 *
 * @module components/graph/nodes/preview-node
 */

import type { NodeProps } from 'reactflow';

/**
 * Data interface for PreviewNode
 */
interface PreviewNodeData {
  /**
   * Partial label text (streaming)
   */
  label: string;

  /**
   * The type this node will become when finalized
   */
  targetType: 'GoalNode' | 'ClaimNode' | 'FactNode' | 'ConstraintNode' | 'AtomicTopicNode';

  /**
   * ID of the agent generating this node
   */
  agentId: string;

  /**
   * Type of agent generating this node
   */
  agentType: string;

  /**
   * Current streaming progress (0-1)
   */
  progress: number;

  /**
   * Whether the agent is still typing
   */
  isTyping: boolean;

  /**
   * Partial reasoning text (streaming)
   */
  partialReasoning: string;

  /**
   * Whether this node is selected
   */
  selected: boolean;
}

/**
 * Preview node component
 *
 * Visual characteristics:
 * - Dashed border (not yet finalized)
 * - Semi-transparent background
 * - Typing indicator animation
 * - Agent avatar badge
 * - Progress indicator
 *
 * This node type is used during SSE streaming to show
 * real-time agent output before the node is finalized.
 *
 * When the agent completes, this node is replaced with
 * the actual node type (ClaimNode, FactNode, etc.)
 *
 * @param props - React Flow node props with PreviewNodeData
 * @returns The preview node JSX element
 */
export function PreviewNode(props: NodeProps<PreviewNodeData>): JSX.Element {
  // TODO: Implement preview node with streaming visualization
  throw new Error('Not implemented');
}
